[package]
name = "haqq-grpc"
version = "0.4.0"
edition = "2021"
license = "MIT"
keywords = ["haqq", "cosmos", "evmos", "grpc", "proto"]
categories = ["finance", "cryptography::cryptocurrencies", "api-bindings", "asynchronous"]
description = "gRPC client for Haqq nodes"
documentation = "https://docs.rs/haqq-grpc"
repository = "https://github.com/haqq-network/haqq-clients"
readme = "README.md"
homepage = "https://haqq.network"

[dependencies]
# ethnum = {version = "~1.5", features = ["serde"]}
alloy-primitives = "~0.7"
derive_builder = "~0.20"
pbjson = "~0.6"
prost = "~0.12"
# prost-wkt-types = { version = "0.5.0", features = ["vendored-protox"] }
prost-types = { version = "~0.12" }
pbjson-types = "~0.6"
rust_decimal = "~1.35"
tonic = "~0.11"
tracing = "~0.1"
serde = "~1"

[dev-dependencies]
color-eyre = "~0.6"
reqwest = { version = "~0.12", features = ["json"] }
tokio = { version = "~1", features = ["macros"] }
tracing-subscriber = { version = "~0.3", features = ["env-filter"] }
tonic = { version = "~0.11", features = ["tls", "tls-roots"] }
# haqq-rest = {path = "./rest"}

[workspace]

members = [
".",
"haqq-build",
# "rest"
]

[features]
default = ["proto_full", "grpc"]
grpc = []
# @@protoc_deletion_point(features)
# This section is automatically generated by protoc-gen-prost-crate.
# Changes in this area may be lost on regeneration.
proto_full = ["amino","capability_v1","cosmos_app_runtime_v1alpha1","cosmos_app_v1alpha1","cosmos_auth_module_v1","cosmos_auth_v1beta1","cosmos_authz_module_v1","cosmos_authz_v1beta1","cosmos_autocli_v1","cosmos_bank_module_v1","cosmos_bank_v1beta1","cosmos_base_abci_v1beta1","cosmos_base_kv_v1beta1","cosmos_base_node_v1beta1","cosmos_base_query_v1beta1","cosmos_base_reflection_v1beta1","cosmos_base_reflection_v2alpha1","cosmos_base_snapshots_v1beta1","cosmos_base_store_v1beta1","cosmos_base_tendermint_v1beta1","cosmos_base_v1beta1","cosmos_capability_module_v1","cosmos_capability_v1beta1","cosmos_consensus_module_v1","cosmos_consensus_v1","cosmos_crisis_module_v1","cosmos_crisis_v1beta1","cosmos_crypto_ed25519","cosmos_crypto_hd_v1","cosmos_crypto_keyring_v1","cosmos_crypto_multisig","cosmos_crypto_multisig_v1beta1","cosmos_crypto_secp256k1","cosmos_crypto_secp256r1","cosmos_distribution_module_v1","cosmos_distribution_v1beta1","cosmos_evidence_module_v1","cosmos_evidence_v1beta1","cosmos_feegrant_module_v1","cosmos_feegrant_v1beta1","cosmos_genutil_module_v1","cosmos_genutil_v1beta1","cosmos_gov_module_v1","cosmos_gov_v1","cosmos_gov_v1beta1","cosmos_group_module_v1","cosmos_group_v1","cosmos_ics23_v1","cosmos_mint_module_v1","cosmos_mint_v1beta1","cosmos_msg_v1","cosmos_orm_module_v1alpha1","cosmos_orm_query_v1alpha1","cosmos_orm_v1","cosmos_orm_v1alpha1","cosmos_params_module_v1","cosmos_params_v1beta1","cosmos_query_v1","cosmos_reflection_v1","cosmos_slashing_module_v1","cosmos_slashing_v1beta1","cosmos_staking_module_v1","cosmos_staking_v1beta1","cosmos_tx_config_v1","cosmos_tx_signing_v1beta1","cosmos_tx_v1beta1","cosmos_upgrade_module_v1","cosmos_upgrade_v1beta1","cosmos_vesting_module_v1","cosmos_vesting_v1beta1","cosmos_proto","ethermint_crypto_v1_ethsecp256k1","ethermint_evm_v1","ethermint_feemarket_v1","ethermint_types_v1","evmos_epochs_v1","evmos_erc20_v1","haqq_coinomics_v1","haqq_liquidvesting_v1","haqq_ucdao_module_v1","haqq_ucdao_v1","haqq_vesting_v1","ibc_applications_fee_v1","ibc_applications_interchain_accounts_controller_v1","ibc_applications_interchain_accounts_genesis_v1","ibc_applications_interchain_accounts_host_v1","ibc_applications_interchain_accounts_v1","ibc_applications_transfer_v1","ibc_applications_transfer_v2","ibc_core_channel_v1","ibc_core_client_v1","ibc_core_commitment_v1","ibc_core_connection_v1","ibc_core_types_v1","ibc_lightclients_localhost_v2","ibc_lightclients_solomachine_v2","ibc_lightclients_solomachine_v3","ibc_lightclients_tendermint_v1","tendermint_abci","tendermint_crypto","tendermint_libs_bits","tendermint_p2p","tendermint_types","tendermint_version"]
amino = []
capability_v1 = []
cosmos_app_runtime_v1alpha1 = []
cosmos_app_v1alpha1 = []
cosmos_auth_module_v1 = []
cosmos_auth_v1beta1 = ["cosmos_base_query_v1beta1"]
cosmos_authz_module_v1 = []
cosmos_authz_v1beta1 = ["cosmos_base_query_v1beta1"]
cosmos_autocli_v1 = []
cosmos_bank_module_v1 = []
cosmos_bank_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_base_abci_v1beta1 = ["tendermint_abci"]
cosmos_base_kv_v1beta1 = []
cosmos_base_node_v1beta1 = []
cosmos_base_query_v1beta1 = []
cosmos_base_reflection_v1beta1 = []
cosmos_base_reflection_v2alpha1 = []
cosmos_base_snapshots_v1beta1 = []
cosmos_base_store_v1beta1 = ["tendermint_abci"]
cosmos_base_tendermint_v1beta1 = ["cosmos_base_query_v1beta1","tendermint_p2p","tendermint_types","tendermint_version"]
cosmos_base_v1beta1 = []
cosmos_capability_module_v1 = []
cosmos_capability_v1beta1 = []
cosmos_consensus_module_v1 = []
cosmos_consensus_v1 = ["tendermint_types"]
cosmos_crisis_module_v1 = []
cosmos_crisis_v1beta1 = ["cosmos_base_v1beta1"]
cosmos_crypto_ed25519 = []
cosmos_crypto_hd_v1 = []
cosmos_crypto_keyring_v1 = []
cosmos_crypto_multisig = []
cosmos_crypto_multisig_v1beta1 = []
cosmos_crypto_secp256k1 = []
cosmos_crypto_secp256r1 = []
cosmos_distribution_module_v1 = []
cosmos_distribution_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_evidence_module_v1 = []
cosmos_evidence_v1beta1 = ["cosmos_base_query_v1beta1"]
cosmos_feegrant_module_v1 = []
cosmos_feegrant_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_genutil_module_v1 = []
cosmos_genutil_v1beta1 = []
cosmos_gov_module_v1 = []
cosmos_gov_v1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_gov_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
cosmos_group_module_v1 = []
cosmos_group_v1 = ["cosmos_base_query_v1beta1"]
cosmos_ics23_v1 = []
cosmos_mint_module_v1 = []
cosmos_mint_v1beta1 = []
cosmos_msg_v1 = []
cosmos_orm_module_v1alpha1 = []
cosmos_orm_query_v1alpha1 = ["cosmos_base_query_v1beta1"]
cosmos_orm_v1 = []
cosmos_orm_v1alpha1 = []
cosmos_params_module_v1 = []
cosmos_params_v1beta1 = []
cosmos_query_v1 = []
cosmos_reflection_v1 = []
cosmos_slashing_module_v1 = []
cosmos_slashing_v1beta1 = ["cosmos_base_query_v1beta1"]
cosmos_staking_module_v1 = []
cosmos_staking_v1beta1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1","tendermint_abci","tendermint_types"]
cosmos_tx_config_v1 = []
cosmos_tx_signing_v1beta1 = []
cosmos_tx_v1beta1 = ["cosmos_base_abci_v1beta1","cosmos_base_query_v1beta1","cosmos_base_v1beta1","cosmos_tx_signing_v1beta1","tendermint_types"]
cosmos_upgrade_module_v1 = []
cosmos_upgrade_v1beta1 = []
cosmos_vesting_module_v1 = []
cosmos_vesting_v1beta1 = ["cosmos_auth_v1beta1","cosmos_base_v1beta1"]
cosmos_proto = []
ethermint_crypto_v1_ethsecp256k1 = []
ethermint_evm_v1 = ["cosmos_base_query_v1beta1"]
ethermint_feemarket_v1 = []
ethermint_types_v1 = ["cosmos_auth_v1beta1"]
evmos_epochs_v1 = ["cosmos_base_query_v1beta1"]
evmos_erc20_v1 = ["cosmos_bank_v1beta1","cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
haqq_coinomics_v1 = ["cosmos_base_v1beta1"]
haqq_liquidvesting_v1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1","cosmos_vesting_v1beta1"]
haqq_ucdao_module_v1 = []
haqq_ucdao_v1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1"]
haqq_vesting_v1 = ["cosmos_base_v1beta1","cosmos_vesting_v1beta1"]
ibc_applications_fee_v1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1","ibc_core_channel_v1"]
ibc_applications_interchain_accounts_controller_v1 = ["ibc_applications_interchain_accounts_v1"]
ibc_applications_interchain_accounts_genesis_v1 = ["ibc_applications_interchain_accounts_controller_v1","ibc_applications_interchain_accounts_host_v1"]
ibc_applications_interchain_accounts_host_v1 = []
ibc_applications_interchain_accounts_v1 = ["cosmos_auth_v1beta1"]
ibc_applications_transfer_v1 = ["cosmos_base_query_v1beta1","cosmos_base_v1beta1","ibc_core_client_v1"]
ibc_applications_transfer_v2 = []
ibc_core_channel_v1 = ["cosmos_base_query_v1beta1","ibc_core_client_v1"]
ibc_core_client_v1 = ["cosmos_base_query_v1beta1","cosmos_upgrade_v1beta1"]
ibc_core_commitment_v1 = ["cosmos_ics23_v1"]
ibc_core_connection_v1 = ["cosmos_base_query_v1beta1","ibc_core_client_v1","ibc_core_commitment_v1"]
ibc_core_types_v1 = ["ibc_core_channel_v1","ibc_core_client_v1","ibc_core_connection_v1"]
ibc_lightclients_localhost_v2 = ["ibc_core_client_v1"]
ibc_lightclients_solomachine_v2 = ["ibc_core_channel_v1","ibc_core_connection_v1"]
ibc_lightclients_solomachine_v3 = []
ibc_lightclients_tendermint_v1 = ["cosmos_ics23_v1","ibc_core_client_v1","ibc_core_commitment_v1","tendermint_types"]
tendermint_abci = ["tendermint_crypto","tendermint_types"]
tendermint_crypto = []
tendermint_libs_bits = []
tendermint_p2p = []
tendermint_types = ["tendermint_crypto","tendermint_version"]
tendermint_version = []
## @@protoc_insertion_point(features)